version: '3.8'

services:
  redis:
    image: docker.io/bitnami/redis:6.0.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - /tmp/redis-data:/bitnami/redis/data

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: summercamp_filestore_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./filestore-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    tty: true

  filestore-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8181:80"
      - "8080:8080"
    environment:
      - GOPROXY="https://goproxy.cn,direct"
      - GO111MODULE=on
      - WAIT_HOSTS=db:3306, redis:6379
    volumes:
      - ./file_tmp:/tmp
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    working_dir: /app
    tty: true
    stdin_open: true
    #command: ./summercamp-filestore

volumes:
  db:
    driver: local
